host         : 0.0.0.0
title        : "Zemaneh Yosef/זמני יוסף"
repo         : "Elyahu41/royzmanimwebsite"
description  : "Use our website to get Halachic times for anywhere in the world, in compliance with the Sepharadi Shita's of Maran Ovadia Yosef, Rabbi Yitzhak Yosef & Rabbi David Yosef"
markdown_ext : "markdown,mkdown,mkdn,mkd,md"

compress_html:
  comments: ["<!-- ", " -->"]

defaults:
  - scope:
      path: "pages"
      type: pages
    values:
      permalink: /:basename:output_ext
      layout: "default"